name: Publish Release Notes

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:
    inputs:
      target-tag:
        required: true
        type: string
        description: Target tag to run on

permissions:
  contents: write  # Required to create release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Checkout target tag
        if: ${{ inputs.target-tag != '' }}
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.target-tag }}

      - name: Create GitHub Release for ${{ inputs.target-tag }}
        if: ${{ inputs.target-tag != '' }}
        run: |
          gh release create "${{ inputs.target-tag }}" \
            --generate-notes \
            --title "${{ inputs.target-tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: ${{ inputs.target-tag == '' }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --generate-notes \
            --title "$GITHUB_REF_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
