name: 'Run tests'

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  test:
    name: Build lint and run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install GoLang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: "go.work"
          cache-dependency-path: "**/go.sum"

      - name: Run build
        run: |
          make build

      - name: Run linters
        run: |
          make check

      - name: Run unit tests
        run: |
          make test-unit

      - name: Run integration tests
        run: |
          make test-integration
